version: "3.8"

services:
  ecommerce-backend-dev:
    build:
      context: ./ecommerce-backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./ecommerce-backend:/usr/src/app
  live-pricing-dev:
    build:
      context: ./live-pricing-service
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./live-pricing-service:/usr/src/app
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000"
      - "443:3000"
    volumes:
      - ./frontend:/usr/src/app
