version: "3.8"

services:
  ecommerce-backend:
    build:
      context: ./ecommerce-backend
    ports:
      - "5000:5000"
  live-pricing:
    build:
      context: ./live-pricing-service
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
      - "443:3000"
    depends_on:
      - "ecommerce-backend"
      - "live-pricing"
