version: "3.8"

services:
  product-api:
    build:
      context: ./product-api
    ports:
      - "5000:5000"
  live-pricing:
    build:
      context: ./live-pricing-service
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
